# Generated by Django 5.2.3 on 2025-07-14 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_info', models.JSONField(blank=True, default=dict, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('education', models.JSONField(blank=True, default=list, null=True)),
                ('skills', models.JSONField(blank=True, default=list, null=True)),
                ('work_experience', models.JSONField(blank=True, default=list, null=True)),
                ('projects', models.JSONField(blank=True, default=list, null=True)),
                ('certifications', models.JSONField(blank=True, default=list, null=True)),
                ('awards', models.JSONField(blank=True, default=list, null=True)),
                ('languages', models.JSONField(blank=True, default=list, null=True)),
                ('publications', models.JSONField(blank=True, default=list, null=True)),
                ('interests', models.JSONField(blank=True, default=list, null=True)),
                ('references', models.JSONField(blank=True, default=list, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
