# Generated by Django 5.2.3 on 2025-07-15 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvbuilder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
