# Generated by Django 5.2.3 on 2025-07-15 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvbuilder', '0002_resume_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='profile_image',
        ),
    ]
