# Generated by Django 5.2.3 on 2025-07-17 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvbuilder', '0003_remove_resume_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
