# Generated by Django 5.2.3 on 2025-07-21 10:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvbuilder', '0005_remove_resume_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='summary',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
